version: '3.6'
services:

  nginxfirst:
    image: nginx:1.21.6-perl
    hostname: prjctr.local
    container_name: nginx_first
    entrypoint: ["nginx", "-g", "daemon off;load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;"]
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www
      - ./proxy.conf:/etc/nginx/conf.d/default.conf

  nginxsecond:
    image: nginx:latest
    hostname: second.local
    container_name: nginx_second
    ports:
      - "81:80"
    volumes:
      - ./public:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
